language: go
go:
  - 1.9.x
  - 1.10.x
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - ./test.sh
sudo: false
notifications:
  email: false
